### PR TITLE
Add new tab by double-clicking on empty part of tabbar.

### PR DESCRIPTION
**Pull request by tarobun**

### CODE REVIEW

**Comment by cser** [comment]
All merged instead of "Treat whitespaces separately to words when removing words on right."
Reasons:
- It's conflicts with current behaviour, that taked from Sublime Text
- It's not fully identical even for Notepad++ (from what editor it taken?)
(current behaviour writed in 4 tests - they are failed on AppVeyor:
UnitTests.ControllerSelectionTest.MoveWordLeftRight
UnitTests.ControllerTest.MoveWordLeftRight_RN
UnitTests.ControllerTest.MoveWordLeftRight0
UnitTests.ControllerTest.MoveWordLeftRight1)

Whe have 2 ways to implement it in common repository:
- realize behaviour as in Notepad++ (I was happy anough with it, if you don't like Sublime mode)
- add special config option for switch to your current behaviour (if it is not mistake and you wasn't try to implement Notepad++ behaviour)

**Comment by tarobun** [comment]
The behaviour I was trying to realise is this.
1) Say you have a line with the text "  test" => [space][space]test
2) Go to beginning of line
3) Hit [Ctrl+Del]

In all the text editors I've used (including Notepad++) this would delete just the spaces first, then the text "test" if you hit [Ctrl+Del] again. In Typewriter.NET, the spaces and text "test" will be deleted at once.

This is the same as the Sublime Text function "Edit | Text | Delete Word Forward".

**Comment by tarobun** [comment]
I'll check the test cases tomorrow.

**Comment by cser** [comment]
Yes, Notepad++ removes space, but Sublime removes space with word O_o.
OK, seems that making behaviour identicaly to Notepad++ is best idea

**Comment by cser** [comment]
Switched to Notepad++

**Pull request merged**
