### PR TITLE
Add Recent submenu to File menu

### PR DESCRIPTION
**Pull request by tarobun**
Add Recent submenu to File menu by:
- changing menu separator from \ to |
- adding Recent submenu placeholder in MainForm
- populating Recent submenu in TempSettings

### CODE REVIEW

**Comment by cser** [comment]
I agree with "|" instead "\\", but no time to merge it, sorry

**Comment by cser** [comment]
More correct item "Recent" submenu showing done.

But I saw '|' in Ctrl+Shift+Up...

Do you like this
```
Edit|Text|Move line up                                        Ctrl+Shift+Up
Edit|Selection|Delete                                                   Del
Edit|Text|Shift right                                                   Tab
Find|Find in files...                                          Ctrl+Shift+F
```
more than
```
Edit\Text\Move line up                                        Ctrl+Shift+Up
Edit\Selection\Delete                                                   Del
Edit\Text\Shift right                                                   Tab
Edit\Text\Upper case                                           Ctrl+Shift+U
Edit\Text\Shift left                                              Shift+Tab
```
?
'|' seems hard for my eyes. Are you shure that cnaging "\" to "|" needed?

**Comment by tarobun** [comment]
I changed this purely to display file paths in Recent menu otherwise it would not render "c:\abc.txt" correctly. If it works with you new changes then no need to change.

**Comment by cser** [comment]
аh, ok

**Comment by cser** [comment]
That explains a lot, but now it works with c:\abc.txt

**Pull request closed without merging**
