### PR TITLE
Add showLineBreaks and showSpaceCharacters to GUI menu and new line number font size setting.

### PR DESCRIPTION
**Pull request by tarobun**

### CODE REVIEW

**Comment by cser** [comment]
- Make showLineBreaks and showSpaceCharacters configs dynamic.
- Improve text rendering (set ClearTypeGridFit hinting).
Will be merged as soon as I can
- Add line number font size to settings.
What is the purpose? Maybe you just need the padding of the numbers? (Anyway fontSize settings will be more difficult - need to change 2 parameters instead 1 - it's can be solwe, but do we need it?)

**Comment by tarobun** [comment]
> - Add line number font size to settings.
> What is the purpose? Maybe you just need the padding of the numbers? (Else fontSize setting > will be more difficult - it will require to change 2 parameters instead 1 - it's can be solve, but do > we realy need it?)

I just like the line number to be different font/size from editor font make it easier to differentiate. I normally have a smaller line number font size than the main font.

**Comment by cser** [comment]
Okey, I'll try to accept this

**Comment by cser** [comment]
Idea: we can set number font size to main font size if number font size = 0

**Comment by tarobun** [comment]
Sounds good. 👍

**Comment by cser** [comment]
I change logic to be possible to make more settings temp if they missing in config or overrided with no value:
<item name="name"/>
Please, say if your color scheme settings will fail after update - it mast be saved

**Comment by cser** [comment]
`showLineBreaks`/`showSpaceCharacters` changes their locations in temp - their values will be lost,
but only once after this upgrade, then they will be saved normally

**Pull request merged**
